# This is a basic workflow to help you get started with Actions

name: blog_updater

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - 'blog_updater_*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  createPullRequest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: pwd
      - run: ls -la
      - run: echo $GITHUB_REF
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: git branch
      - run: find .git/refs/heads
        
#       # Make changes to pull request here
#       - name: Create Pull Request
#         uses: peter-evans/create-pull-request@v3
#         with:
#           branch: GITHUB_REF
