# This is a basic workflow to help you get started with Actions

name: blog_updater

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - 'blog_updater_*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  createPullRequest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repo on new branch
        uses: actions/checkout@v2
        
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

        
      - name: Create Pull Request into master
        uses: peter-evans/create-pull-request@v3
        with:
          branch: master
          base: ${{ steps.extract_branch.outputs.branch }}
          commit-message: Update blog list
          title: Update blog list
          assignees: gpetrousov
